#!/bin/bash

# Function to install gitleaks using curl pipe sh method
install_gitleaks() {
    echo "Installing gitleaks..."
    echo "If installation fails, run the following command in your terminal"
    echo 
    echo "curl -sSfL https://raw.githubusercontent.com/alexanderlukjanenko/gitleaks-pre-commit-hook/main/install.sh | sh"
    echo 

    curl -sSfL https://raw.githubusercontent.com/alexanderlukjanenko/gitleaks-pre-commit-hook/main/install.sh | sh
}

# Check if gitleaks is installed
if ! command -v gitleaks &> /dev/null; then
    echo "gitleaks is not installed"
    install_gitleaks
fi

# Check if gitleaks is enabled via git config
if [[ "$(git config --get hooks.gitleaks.enabled)" == "true" ]]; then
    # Run gitleaks
    echo "Running gitleaks..."
    gitleaks protect -v --staged
else
    echo "Gitleaks is not enabled via git config"
    exit 0
fi